import type { Metadata } from "next";
import { Tektur } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Tektur({ subsets: ["latin"], weight: ['400', '500', '600', '700'] });

export const metadata: Metadata = {
    title: "OutlawCraft",
    description: "Generated by create next app",
};

export default function RootLayout({children,}:
    Readonly<{ children: React.ReactNode; }>
) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Header/>
                {children}
            </body>
        </html>
    );
}
