import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Comfortaa({ subsets: ["latin"], weight: ['400', '500', '600'] });

export const metadata: Metadata = {
    title: "OutlawCraft",
    description: "Generated by create next app",
};

export default function RootLayout({children,}:
    Readonly<{ children: React.ReactNode; }>
) {
    return (
        <html lang="en">
            <body className={inter.className}>
            <Header/>
                {children}
            </body>
        </html>
    );
}
